DROP TABLE BREAK_WORDS;
DROP TABLE WORDS;
DROP TABLE DOCUMENT;
CREATE TABLE BREAK_WORDS (
  ID SERIAL PRIMARY KEY,
  WORD VARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE DOCUMENT (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE WORDS(
  WORD VARCHAR(255),
  DOCUMENT_ID INTEGER REFERENCES DOCUMENT(ID),
  COUNT INTEGER
);

INSERT INTO BREAK_WORDS(word) VALUES
  ('in'),
  ('with'),
  ('a'),
  ('an'),
  ('for'),
  ('be'),
  ('will'),
  ('has'),
  ('since'),
  ('very'),
  ('so'),
  ('was');

UPDATE WORDS SET WORDS.WORD='document1' WHERE WORDS.DOCUMENT_ID=1;


